### ISSUE TITLE
issues with uuid expandsion

### ISSUE THREAD

**Issue by cryoguy** [nobiot/org-transclusion#55] opened 2021-02-05 19:09 UTC
I am having issues with uuid transclusion. In the following, the first one is expanded fine, but not the second one.  I can click and open the link in emacs though. ??

```
[[file:steps_with_ffmpeg.org][Setting up ffMPEG and Mediainfo]]
# [[id:560ca036-101c-448d-99ff-8a3026e23cfc][windows environment variable setting]]

```

**Comment by nobiot** [comment] 2021-02-05 19:48
Try without `# ` in the beginning. 
In the current version, the link has to be in the beginning of the line (even with the `#+transclude: t`.

[Documentation in the README](https://github.com/nobiot/org-transclusion#org--mode-links).

I might revisit this design later, but haven't really decided if supporting mid-line is a good thing (conflict with returning the original link when you deactivate transclusion)

**Comment by cryoguy** [comment] 2021-02-05 23:51
It did not work without # and positioned upfront, and that is why I have to use the link as in the first line. I can open the link though.

**Comment by nobiot** [comment] 2021-02-06 08:27
I cannot reproduce the problem.

I just tried with the latest commit, and with `emacs -q`.
![2021-02-06T0919_emacs-q](https://user-images.githubusercontent.com/12507865/107113054-9752d480-685c-11eb-9892-95d44a9d6e27.gif)

Can you try `emacs -q` and see if you can get transclusion to work for ID, please?
To load, you can use `load-file` and find the `org-transclusion.el` file.
For Org-id, `org-id-copy` should work -- also should copy it to its "database".

**Comment by cryoguy** [comment] 2021-02-06 18:43
ok. Here is what happens.  `org-transclusion` won't expand `org-roam` file id, i.e., it won't recognize the file id inserted with `C-c n i`. It does work with ids for headlines though.  I thought file ID is an intrinsic feature for emacs org-mode, maybe I have been wrong since I can't seem to open without `org-roam`.

**Comment by nobiot** [comment] 2021-02-06 19:47
What are the steps you take to generate Org-id in Org-roam?
I want to support Org-roam and IDs. 

Org-roam stores IDs in its cache DB, and overrides Org-id's way to find it. But it uses `org-open-at-point-functions` to do this. I should be able to get Org-transclusion to somehow be compatible with this way. If you can let me know how you do it, that will help me understand how it is used in reality.

**Comment by nobiot** [comment] 2021-02-06 19:57
This is what I see for an ID for a headline only known to Org-roam.
I thought I had made Org-transclusion work with this case; as far as I could test, it works.

![2021-02-06T205300_org-roam](https://user-images.githubusercontent.com/12507865/107128400-acac1b00-68bd-11eb-85d1-88e456b91e00.gif)

Perhaps you are using the file-level (level 0) property to link to the file, not headline?
Or perhaps there is an edge case that I could not identify.

**Comment by nobiot** [comment] 2021-02-06 20:22
I believe it is the case when ID refers to the whole ID (level 0).
This case was not previously considered, and does not work at the moment -- I just tried, and confirmed this.

I will need to take some time to think it through -- I cannot provide an easy fix.
It's not just the resolving the ID. The filtering mechanism is not designed to work with is at the moment. So... When I tried a fix of the ID resolution, the content is not correctly transcluded.

I will need to put it in the backlog and come back to it in April / May timeframe when I will have more time...

**Comment by cryoguy** [comment] 2021-02-07 17:10
@nobiot Thanks for your efforts.  I have been using this package regularly now.  It is a missing piece in the workflow!

**Comment by nobiot** [comment] 2021-02-07 21:10
Thank you for your encouragement. I cannot really work on an important change like this at the moment; I'm delayed for a big deadline in other part of my life. I'm a bit too nervous.

I'll work on this point as priority, though, as soon as I get over it. Org-roam is planned to switch to supporting only IDs (file and headlines) with its upcoming version 2, so I need to support this for myself.

I'll appreciate your understanding and patience.

**Comment by cryoguy** [comment] 2021-02-08 16:17
It is no rush.   Appreciate all your work!

**Comment by nobiot** [comment] 2021-04-18 11:21
The new commit should fix the issue of ID pointing to the whole file. 
Closing this issue for now. If issue persists, please reopen and comment. Thank you.

**Closed by nobiot** 2021-04-18 11:21 UTC
Labels: bug
