### ISSUE TITLE
Buffer readonly right after transcluded section

### ISSUE THREAD

**Issue by shlevy** [nobiot/org-transclusion#49] opened 2020-12-29 13:41 UTC
If I have:

```org-mode
* Foo
#+transclude: t :hlevel 2
[[file:baz][baz]]
* Bar
```

then when transclusion is on I can't make any changes when point is on the first `*` of the `Bar` heading

**Comment by nobiot** [comment] 2020-12-30 11:44
Yes, this is also an expected behavior because the way text-properties work in Emacs in general (`rear-sticky`). I might be able to make it a little more fluid with some coding with help of `insert-behind-hooks`, but I find it a bit difficult for me to work with at the moment (do you have Elisp experience, and can suggest something? -- that would be fantastic).

At the moment, my suggestion is to have a blank line after the link. This is also related to issue #46

**Comment by nobiot** [comment] 2021-05-09 18:09
v0.1.0 is now merged with main. It has streamlined the syntax with using only `#+transclude:` keyword. The keyword can be used without a blank line in-between (I have tested this). 

It would be great if you could try the new version in the main branch and let me know how you go.
Closing this issue for now. Thank you.

**Closed by nobiot** 2021-05-09 18:09 UTC
