### ISSUE TITLE
optimize org-transclusion-mode faster for checking when saving buffer

### ISSUE THREAD

**Issue by stardiviner** [nobiot/org-transclusion#58] opened 2021-02-13 01:14 UTC
I tried to use `(add-hook 'org-mode-hook #'org-transclusion-mode)` to enable `org-transclusion-mode` on all Org buffers.
But it caused obviously delay on saving buffers.
Is it possible to optimize it?
Enable this minor mode on org-mode will don't need to manual toggle mode frequently.

**Comment by nobiot** [comment] 2021-02-13 09:52
Sure. My programming skills are limited, but I’ll see what I can do with your help.

Let me first understand the issue a bit more precisely. In theory, the number of buffers with the org-transclusion minor mode active should not influence  the performance of save-buffer. My assumption is you save one buffer at a time; the other buffers don’t affect this single save operation.

Questions I would ask you to help me would be:

- Do you save one buffer at a time? Or do you save multiple buffers (with transclusion activated) somehow?
- When you experience “delay on saving buffers”, how many links do you transclude in a single buffer?
- Are all the linked buffer open before transcluding them? Does the performance change the first time when you transclude links and second time onwards?

The way transclusion works is that it visits all the linked buffer, and copies all the relevant content for you. This means if a linked file is not visited, it will take more time to open it in a buffer. In this case, you might further experience delay if you deferred major mode and other packages for that buffer (e.g. if you defer Python mode only when you first visit a py file, it will take time to turn it on, etc.)

Let us start with these questions. Thank you for your interest, and questions/requests.

**Comment by stardiviner** [comment] 2021-02-15 14:22
I only save one org buffer at a time. And it coast about 2 seconds. Usually my Org file is big. It cloud contains lot of source blocks and other org elements which slow down Org performance.

My thinking is that org-transclusion-mode triggered everytime I save Org buffer. But sometimes I don't need to re-fresh org-transclusion stuff, just some simple editing. Is there a way to trigger org-transclusion refresh only when the transclusion block changed?

**Comment by stardiviner** [comment] 2021-02-15 14:23
> The way transclusion works is that it visits all the linked buffer, and copies all the relevant content for you. This means if a linked file is not visited, it will take more time to open it in a buffer. In this case, you might further experience delay if you deferred major mode and other packages for that buffer (e.g. if you defer Python mode only when you first visit a py file, it will take time to turn it on, etc.)

This indeed is a problem. Opening a file and retrieve file content and display. I can understand that affect performance.

**Comment by nobiot** [comment] 2021-02-15 15:14
> My thinking is that org-transclusion-mode triggered everytime I save Org buffer. But sometimes I don't need to re-fresh org-transclusion stuff, just some simple editing. Is there a way to trigger org-transclusion refresh only when the transclusion block changed?

At the moment, my sense is that the answer is very close to No, for this specific suggestion.

The reason is rather simple. Just before Emacs saves the buffer to the file, Org-transclusion needs to remove the transcluded content, and insert the original link for every transclusion. Right after this is done, it transcludes every content again.

Why? Otherwise, the content would be saved to the file, losing the link. This is a problem, because otherwise the links wouldn't survive across sessions; if you quit Emacs, you would end up only keeping copies of content.

To extend your suggestion, this could be maybe achieved by shifting this remove-before-save-logic to only when you kill-buffer and kill-emacs, for example. Will this survive when Emacs crashes? Is it an only edge case, and I should not care about it? I'm not sure.

As an alternative.... If your org file is very large, I understand that things could be slow -- Org-transclusion checks for every link in the file. Maybe I could change this logic to look for only keyword (`#+transclusion`) instead. This might improve the performance when the org file is large with a lot of links (where most of them are not for transclusion).

**Comment by stardiviner** [comment] 2021-02-15 15:34
> As an alternative.... If your org file is very large, I understand that things could be slow -- Org-transclusion checks for every link in the file. Maybe I could change this logic to look for only keyword (`#+transclusion`) instead. This might improve the performance when the org file is large with a lot of links (where most of them are not for transclusion).

This sounds reasonable.

**Comment by stardiviner** [comment] 2021-02-15 15:39
> The reason is rather simple. Just before Emacs saves the buffer to the file, Org-transclusion needs to remove the transcluded content, and insert the original link for every transclusion. Right after this is done, it transcludes every content again.
> 
> Why? Otherwise, the content would be saved to the file, losing the link. This is a problem, because otherwise the links wouldn't survive across sessions; if you quit Emacs, you would end up only keeping copies of content.

How do you display the transclusion content? text-property? or overlay etc? I have written one extension [org-link-beautify](https://github.com/stardiviner/org-link-beautify) which use `text-property` to display link preview or icons WITHOUT REALLY insert anything. If you're not using text-property. I think that it might be a good solution. I also used similar way in `google-translate` extension for Org buffer paragraphs translation. Here is the links https://github.com/atykhonov/google-translate/search?q=paragraphs&type=commits

**Comment by nobiot** [comment] 2021-02-15 16:03
Thank you for the link. I can't use 'display property either of `text-property` or `overlay`. The text content transcluded needs to be a real text content for the writing purpose (the primary purpose of this package). You cannot export or use `pandoc-mode` for the text displayed only with the display property -- I tried in early prototypes.

**Comment by stardiviner** [comment] 2021-02-16 01:13
I see. Indeed, those solution can't archive this purpose.

**Comment by oatmealm** [comment] 2021-03-05 12:19
Might it be possible to save transclusion links in the buffer as metadata at the end of the file, the way ov-highlight works? 

This way you save the link points as data, and reconstruct them when buffer is created and the mode is activated? Ie no need to hook into the save buffer process...

**Comment by nobiot** [comment] 2021-03-06 16:32
@oatmealm 

I would like to keep the Org files readable as text. Links are good for this purpose.

I am not sure the ended data gives us any additional benefits. What is your thought on this?

`ov-highlight` saves the highlight and annotations as encoded text string at the bottom of the Org file, so these data can survive quit/relaunch of Emacs.  I believe This works only when you open the Org buffer in Emacs (or do something for the encoded text).

**Comment by nobiot** [comment] 2021-05-09 18:07
v0.1.0 merged with the main branch. I have streamlined the syntax, and now it uses `#+transclude:` keyword, which you can generate out of a link. 

I am hoping that this should help increase the performance as  the number of `#+transclude` keyword occurrences should be much smaller than links. 

Closing this issue for now. Let me know if have chance to test the new version and performance issue still persists. 
Thank you.

**Closed by nobiot** 2021-05-09 18:07 UTC

**Comment by oatmealm** [comment] 2021-05-09 20:02
Hi. Thanks for the update.

I'm seeing this when applying `org-transclusion-add-at-point` on this:

`#+transclude: t [[id:003a1c19-6f34-4f08-a17b-3fcf41bba105][عَادِل - عُدُول]]`

```
Debugger entered--Lisp error: (void-function nil)
  nil(nil)
  org-transclusion-add-at-point()
  funcall-interactively(org-transclusion-add-at-point)
  command-execute(org-transclusion-add-at-point record)
  counsel-M-x-action("org-transclusion-add-at-point")
```
I've got it setup like this (in Doom):

```
(package! org-transclusion
  :recipe (:host github
           :repo "nobiot/org-transclusion"
           :branch "main"
           :files ("org-transclusion.el")))
```

**Comment by nobiot** [comment] 2021-05-09 20:40
Thanks for the report. Can you tell which commit you are on?

I have not seen this error before.

**Comment by oatmealm** [comment] 2021-05-10 11:12
Yes. Of course. I did restart etc. Right no it's at: 5ec849a72dbd7664caae6525346ffdeeabec07ef

**Comment by oatmealm** [comment] 2021-05-10 11:17
Update: I saw I was one commit behind. Trying again.

```
      → Building deadgrep...done
      → Building org-transclusion...
Compiling /home/uri/src/doom-emacs/.local/straight/build-28.0.50/org-transclusion/org-transclusion.el...

In org-transclusion-content-get-org-buffer-or-element-at-point:
org-transclusion.el:833:41: Warning: Unused lexical variable `parse-mode'
      → Building org-transclusion...done
      ✓ Rebuilt 2 package(s)
```

Now I see the error is back. 

`org-transclusion-add-at-point: Symbol’s function definition is void: nil`

**Comment by nobiot** [comment] 2021-05-10 12:01
Very strange. I cannot reproduce the problem.
I will fix that warming you see in building the package in doom sync, but I am not sure if it is the cause.

The "Nothing done. No content is found through the link" appears only one location in the source code, and that's where the it could not obtain any text content from the link (the link itself would have worked, but there is no text in the returned value). 

I have no idea what causes the "Symbol's function definition is void: nil" error comes from.  It appears to me that Org-transclusion is trying to call `nil` as a function...

What's your Emacs version?

**Comment by nobiot** [comment] 2021-05-10 12:34
@oatmealm , I have also byte-compiled the `org-trasnclusion.el`, got the same warning; I can run the package with no issues. I will try later today with Ubutu with native compiled Emacs on 28.x (I think).

**Comment by oatmealm** [comment] 2021-05-10 14:37
Yes. I'm on 28.x nativcomp. 

```
Doom v2.0.9 (grafted, HEAD -> develop, origin/develop, origin/HEAD b2c4e0f 2021-05-07 02:37:47 -0400)
GNU Emacs 28.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-04-25
```

**Comment by nobiot** [comment] 2021-05-10 16:36
@oatmealm 

I have managed to reproduce the error message.
It happens when Emacs does not recognise the ID. Try correcting the ID (see if you can navigate to it as a link).

I will add a bit more useful error handling but you should be able to transclude the ID link without any change on the program.

**Comment by oatmealm** [comment] 2021-05-10 16:51
Hi. I think the link is ok. No problem manually navigating (mouse or keyboard).


https://user-images.githubusercontent.com/68159077/117695656-c01e9900-b1c0-11eb-9ab7-e7deddc37a67.mov

**Comment by nobiot** [comment] 2021-05-10 17:07
Could we move to #73 ?
My guess is that your file might be within Org-roam directory, and the ID is only recognised by it but not Org-ID.
Could you evaluate this in the original file (not the transcluding one that is failing) to update Org-ID location cache, and see if it changes anything?
Also the  latest commit (just 10 minutes ago or so) adds a bit more useful message and does not error.
I suggest you update.
```
(org-id-update-id-locations (list (buffer-file-name (current-buffer)))))
```
