### ISSUE TITLE
Question on `nested transclusion`

### ISSUE THREAD

**Issue by randomwangran** [nobiot/org-transclusion#91] opened 2021-08-20 01:48 UTC
Hi @nobiet:

   I have just come up with this idea and want to share it with you.

   If a transcluded node contains another transclusion, the nested transclusion will be ignored in the current version.

   Have you ever think about implementing a nested function that shows all the content?

   Does the nested transclusion a bad idea? Or is this more a technical issue?

**Comment by nobiot** [comment] 2021-08-21 12:59
The reason nested transclusions are ignored is simply to avoid infinite recursion.
A simple case would be file A and B have transclusions from each other. 
It's possible that this will lead to infinite recursion (or so I thought): A contains B contains A contains B contains ... and so on

Thinking precisely about recursion is difficult for my brain. I simply made it easy (for me) by disallowing nested transclusions altogether.

**Comment by fakedrake** [comment] 2021-10-06 14:22
A recursive transclusion would mean a link being traversed twice. In that case I think it makes sense for an error to be thrown.

In any case I am having a problem with including nested transclusions: When text A is transcluded and then some nested text B is transcluded at point `a`, deleting transclusion B will put transcluded text A in a weird state where it is split in half at point `a`.

**Comment by nobiot** [comment] 2021-10-06 14:48
@fakedrake Could you provide an example, please?

**Comment by fakedrake** [comment] 2021-10-06 16:00
I think I found the problem. Its the combination of some breaking assumptions of `org-transclusion-remove` in the presence of nested transclusioins:

- the character right before the beginning of a transclusion is not necessarily an adjacent transclusion. It might be the parent transclusion. 
- Usin `insert-before-markers` to re-insert the `#+transclude: ...` element loses information about the text properties present before inserting the cloned text. This is still prone to bugs but using  `insert-before-markers-and-inherit` instead avoids the common case errors.

I will make a pr with the fixed `org-transclusion-remove`.

**Comment by nobiot** [comment] 2021-11-04 19:31
For now, I don't think it's feasible for me to support nested transclusion. I am closing this issue.

**Closed by nobiot** 2021-11-04 19:31 UTC

**Comment by randomwangran** [comment] 2022-05-30 15:53
I would like to criticize myself for this idea.

If there's a chance for nested transclusion, it would be a very good opportunity to re-arrange/re-thinking of my thoughts. Thus, a great chance to generate new ideas.

**Comment by Cletip** [comment] 2023-07-20 14:11
Hello!
I haven't seen it mentioned anywhere, so I'm writing it here (you never know): you can do nested transclusions with this hook:
`(add-hook 'org-mode-hook 'org-transclusion-mode)`

I haven't tested for potential issues, so proceed at your own risk ^^ (editing won't work, but viewing looks OK)

**Comment by nobiot** [comment] 2023-07-20 18:19
> you can do nested transclusions with this hook:
> `(add-hook 'org-mode-hook 'org-transclusion-mode)`

Wow! Not by design but I am not “fixing” it to block it for now… Let me know how your experience goes…

**Comment by dschaehi** [comment] 2025-02-24 11:16
I think there are situations where nesting is useful. I am wondering if it would be possible to allow nesting while avoiding infinite loops, e.g., by detecting loops or by allowing nesting only up to a certain depth.
