### ISSUE TITLE
emacs switches to note instead of transcluding (only with id: links)

### ISSUE THREAD

**Issue by lytex** [nobiot/org-transclusion#19] opened 2020-11-02 11:21 UTC
Launching doom without any user configuration, org-transclusion is jumping to the transcluded buffer, instead of transcluding the headline:

![ts](https://user-images.githubusercontent.com/32138262/97862184-34095180-1d05-11eb-8362-64a9eb45414e.gif)

The lower headings are missing:
```
* This is my headline
* This is another headline
```

Any idea why is this happening? Does doom emacs do not support indirect buffers?

**Comment by nobiot** [comment] 2020-11-02 17:37
If there is no user configuration, then... I think you would need to toggle the minor mode on?

**Comment by nobiot** [comment] 2020-11-02 17:43
Sorry, it's very hard to see what's happening in the gif. You are toggle the minor mode on?
It's strange. You should see this header on top of your buffer:
![image](https://user-images.githubusercontent.com/12507865/97900632-371f3480-1d3b-11eb-9065-050b8d282a23.png)

**Comment by lytex** [comment] 2020-11-02 22:23
Yes, that was definitely too short, sorry about that! I have embedded a bigger resolution, longer video at the end.

Ok, so I have these two files, open side by side:

test1.org
```
#+TITLE: Test1

* A Headline

[[id:5f719988-08b4-4dbd-aa07-255e2cb275e8][I want to transclude this headline]]

* This is my headline
* This is another headline
```

test2.org
```
#+TITLE: Test2

* I want to transclude this headline
:PROPERTIES:
:ID:       5f719988-08b4-4dbd-aa07-255e2cb275e8
:END:
** Which also has subheadlines
```

1. org-transclusion-mode is initially deactivated
2. I toggle the visibility of the link, to see what's inside and to ensure that both ids are indeed the same
3. Then with M-x I toggle org-transclusion-mode

Then I would expect that the left buffer, with test1.org, would look like:

```
#+TITLE: Test1

* A Headline

* I want to transclude this headline
:PROPERTIES:
:ID:       5f719988-08b4-4dbd-aa07-255e2cb275e8
:END:
** Which also has subheadlines

* This is my headline
* This is another headline
```

but instead it merely opens the test2.org file! Then I got back to the previous buffer and I see the header:
`Transclusion active in this buffer. 'C-c n e' to edit the transclusion at point.`

But there is no transclusion neither!

Finally if I toggle the org-transclusion mode off and on again, the same things happen (it switches to test2.org without transcluding anything)

![ts2](https://user-images.githubusercontent.com/32138262/97925688-1fa77200-1d62-11eb-8993-cd1684334a4b.gif)




Since the code is changing at a particular fast pace right now, do you think it's better to wait if this is still happening when the codebase is a little more stable? This could be easily an doom emacs bug unrelated to org-transclusion.

**Comment by nobiot** [comment] 2020-11-03 07:24
This is really weird. I happen to have Doom config kept in my PC (I used to use Doom). I will see if I can repro the same behaviour on my end.

**Comment by nobiot** [comment] 2020-11-03 16:21
My doom is a bit old (some info in the attached image), but seems to work.
My Emacs is 27.1, and Org 9.4.
![image](https://user-images.githubusercontent.com/12507865/98010910-8cb91700-1df7-11eb-9e67-28bd8b256e55.png)

Do you have functions `org-open-at-point` or `org-link-open` advised by any chance?
You can see it in `C-h f` (`describe-function`) -- Doom might map the keybinding to `helpful-function`, but it should also tell you the advice state.

![image](https://user-images.githubusercontent.com/12507865/98011896-c3dbf800-1df8-11eb-8486-5bc59155e1b1.png)

**Comment by nobiot** [comment] 2020-11-03 16:23
Also... You might like to try `::*Heading`; Org-ID behaves slightly differently to other links, so I needed to cater specifically to it.

**Comment by lytex** [comment] 2020-11-04 21:32
> Also... You might like to try `::*Heading`; Org-ID behaves slightly differently to other links, so I needed to cater specifically to it.

I just tested it, heading links work fine, but file links also do weird things.

> Do you have functions `org-open-at-point` or `org-link-open` advised by any chance?

`org-open-at-point` is not advised, but `org-link-open` is according to describe-function. However I don't know how to deactivate it, as `(ad-deactivate 'org-link-open))` is saying that it is not advised

**Comment by nobiot** [comment] 2020-11-06 07:35
Removing advice should be something like this: `(advice-remove 'org-link-open #'org-transclusion-link-open)`.

Thanks for pointing out the weird behaviour with "file links" -- I take it as that when a link is for an entire org file (without the "::" part). I am working on it -- it's a bit more tricky for transclusion, because of the part in the file before the first headline.  I will do something about it as I want it to work.

**Comment by randomwangran** [comment] 2020-11-08 03:02
Apart from #22, I can also confirm with the following statement:

> Launching doom without any user configuration, org-transclusion is jumping to the transcluded buffer, instead of transcluding the headline:

This is not a specific issue with Doom. I have similar issue with `id::uuid` link.

**Comment by nobiot** [comment] 2020-11-08 17:45
Thank you both.

It's difficult to pin down where the problem really is; i can't reproduce this behaviour as you can see in my de o videos...

Having said this, I will try to focus on the content extraction after my current work on adding '#+transclude:' keyword. 

I will come back to this issue in due course.

Thanks again 😄

**Comment by randomwangran** [comment] 2020-11-11 03:11
I suddenly realize that I've installed [window-purpose](https://github.com/bmag/emacs-purpose), which might be an issue. I did't test it yet, but I think it might be the source of the issue.

**Comment by nobiot** [comment] 2020-11-11 18:29
@randomwangran, okay. Thanks. Would it be possible to turn it off and see if that changes the behaviour in question?

**Comment by randomwangran** [comment] 2020-11-13 03:00
I have a new note with a link using this type of link format:

[[id:UUID][test]]

I can jump into the headline of this link using `org-open-at-point`.

In the new note, if I execute the function `org-transclusion-mode`,
the buffer will switch to that headline in its original file instead
of showing the content. This is the behavior with my config file
loaded. It is similar to @lytex reported.

I further test the vanilla emacs, but I could not do the transclusion
with id link.

I only load `org-transclusion-mode`
(dfd2adee551b7a0c36d45d32d6f48badc2c5dfe0) in to the environment, i.e.
`Emacs 27.1` with `org-mode 9.4` with `emacs -q`, I repeat the same
precedure, but I can not see the id headline being transcluded. Instead, it
flushes out the link string completely.

**Comment by nobiot** [comment] 2020-11-13 07:08
Thank you. I will try with emacs -q on my end too

**Comment by nobiot** [comment] 2020-11-15 10:51
@lytex, @randomwangran

Merged v0.0.5 (249de00) with a new YT video. I have changed the way source buffers are "opened" via the link. I am hoping that this solves the problems you reported. On my Windows machine, Emacs 27.1 Org-mode 9.4, and `emacs -q` I cannot reproduce the problem, so I am stabbing in the dark; but my assumption is this was the culprit:

`save-window-excursion`
The doc has this below:

> BEWARE: Most uses of this macro introduce bugs.
> E.g. it should not be used to try and prevent some code from opening
> a new window, since that window may sometimes appear in another frame,
> in which case ‘save-window-excursion’ cannot help.

**Comment by nobiot** [comment] 2020-11-15 10:51
I would appreciate it if you could see if the latest version solves the problems.
Thank you!

**Comment by lytex** [comment] 2020-11-15 20:51
Still not working with `[[id:]]` links, but `[[file:file.org]]` and `[[file:file.org::*headline]]` are working.

Interestingly, if the transcluded headline is in the same file, transclusion works, even with id.

I tried to use `emacs -q` like @randomwangran, but I couldn't get `org-open-at-point` working as it doesn't find the headline in a different file.

**Comment by randomwangran** [comment] 2020-11-17 21:08
@nobiot 

I just tested 781993eb934a8dc1be7029e6ea217fec70416353 with two conditions:

One is `emacs -q`, ID link is working perfectly. The buffer shows the transcluded content as expected.

The other one is with my personal configuration.

It is still not showing the content that the ID pointing to. Instead, it just switchs to the buffer that ID pointing to. It's the issue with my configuration. I will try to find the reason.

@lytex 

> , but I couldn't get org-open-at-point working as it doesn't find the headline in a different file.

Did you load `org-id-locations-file` to your environment with `emacs -q`?

**Comment by nobiot** [comment] 2020-11-17 21:56
Thank you both... My assumption currently is that if you cannot transclude a headline with using its ID, you cannot also open it with Org-id, or there is something (outside Org-transclusion) interfering Org-id to work. I am using `org-id-find` to locate where the ID points to (marker).

**Comment by nobiot** [comment] 2020-11-18 06:58
@randomwangran , perhaps it’s “org-file-apps” a quote from a recent exchange on Slack: 

> I found one of the culprits: "org-file-apps." It somehow invokes any "file:path" to open in a new frame, which is causing the errors. Just noting it in case anyone runs through a similar problem

**Comment by randomwangran** [comment] 2020-11-18 15:21
Thanks for providing this information @nobiot . I've done two tests:

1. comment out this line in my config file, restart Emacs with my config.
`(setq org-file-apps '(("\\.org\\'" . emacs)))`

Negative response.

2. change `(setq org-link-frame-setup '((file . find-file)))` to
`(setq org-link-frame-setup '((file . find-file-other-window)))`

Negative response as well.

I will bisect my config file to see how is it going.

**Comment by nobiot** [comment] 2020-11-19 12:50
The quickest way to get to the bottom of this is to set a `edubb` at the function `org-transclusion-link-open` and see the runtime behaviors line by line. Sorry, I really cannot repro the problem, so I would need to rely on you, and people who have this problem...

**Comment by randomwangran** [comment] 2020-11-20 02:30
I've catched the problem.

 `'(org-roam-mode t nil (org-roam))` is the reason. When I comment out this line in my [config](https://github.com/randomwangran/WRE/blob/530bb5820a7577c6c7e82bb2d714cdfb1b342787/.emacs#L2877), the transclusion has no problem.

But this loaded, the problem exist.

**Comment by nobiot** [comment] 2020-11-20 07:52
@randomwangran , what do you intend to do with that?

As you put it within `custom-set-variables`,  I evaluated this: `(setq (org-roam-mode t nil (org-roam)))`.
I get an error: `Debugger entered--Lisp error: (wrong-number-of-arguments setq 1)`.

It looks to be a syntax error; I think it is not doing anything meaningful in your config (?).

**Comment by randomwangran** [comment] 2020-11-20 15:42
Hi @nobiot, I could not understand the `(org-roam-mode t nil (org-roam))` either. It was automatically added to my configuration file during package installations, but I was not able to recall how it was triggered.

Variables set by `custom-set-variables` were treated different from directly using `(setq ...)`.

```
(defun custom-set-variables (&rest args)
  "Install user customizations of variable values specified in ARGS.
These settings are registered as theme `user'.
The arguments should each be a list of the form:

  (SYMBOL EXP [NOW [REQUEST [COMMENT]]])

This stores EXP (without evaluating it) as the saved value for SYMBOL.
If NOW is present and non-nil, then also evaluate EXP and set
the default value for the SYMBOL to the value of EXP.
```

`(org-roam-mode t nil (org-roam))` does not make sense to me according to this documentation.

Now, I just delete this line and see what happens.

**Comment by randomwangran** [comment] 2020-11-20 19:23
Another unexpected behavior is that:

  If I 
  (1) open Emacs with my config file 
  (2) (ido-find-file "PATH-TO-FILE") 
  (3) (org-roam-transclusion), there is no issue.

But, with this procedure

  (1) open Emcas with my config file
  (2) (org-roam-dailies-today)
  (3) (org-roam-find-file)
  (4) typing the name of the testing file
  (5) (org-roam-transclusion)

  It will repeat the issue.

  Under the same file with the same buffer, I've checked that they both have the same minor-modes opened.

**Comment by randomwangran** [comment] 2020-11-20 19:30
By the way @nobiot I am not very familar with `edebug`, so I will do it later and provide useful information if necessary.

**Comment by nobiot** [comment] 2020-11-22 12:03
Thanks for the steps.
This has allowed me to reproduce the problem.
It's Org-roam specific (and for opening ID).

Org-roam stores IDs in the cache DB and uses it to open IDs (instead of the normal Org-ID way of a file, etc.).
It's all well, with using Org's facility to add a function to open a link at point:
`(add-hook 'org-open-at-point-functions #'org-roam-open-id-at-point)`

I will need to address this in a clever way. Let me think of a way; I want to address it in the next update or so.

With this finding, I believe the problem is confined within Org-roam and ID at the moment (I am ignoring all other possibilities that touch the same facilities, but I need to see if I can make a solution future proof...).

**Comment by randomwangran** [comment] 2020-11-22 14:23
No worry about it, @nobiot

I will also study the code logic on this issue and to make it a future proof solution.

**Comment by nobiot** [comment] 2020-11-22 18:40
I opened PR #30. With my initial testing, it fixes the issue of Org-ID with and without Org-roam; it should be a generic fix.
I still need to clean up before merging to the main (you can try the branch to see it yourself, if you wish; of course you can wait for merge with the main).

This issue has given me a good opportunity to make Org-roam a bit cleaner; I think I can remove `advice-add` and still stick to the standard facilities (hook) that Org Mode provides. So thank you for staying around and testing along the way @randomwangran @lytex !

**Comment by randomwangran** [comment] 2020-11-23 01:02
Well done @nobiot !

**Comment by nobiot** [comment] 2020-11-23 19:53
Works in your end?

**Comment by lytex** [comment] 2020-11-29 11:58
Hi! Busy week

Unfortunately doesn't work on my emacs
I have been testing it with different configs to see if it was a matter of my emacs config or a more general bug.
Using doom emacs with no user configuration, emacs does not jump to the new note, but instead now deletes the transclusion text:

![otc4](https://user-images.githubusercontent.com/32138262/100541160-34cccf00-3242-11eb-9561-ce2190236469.gif)

**Comment by nobiot** [comment] 2020-11-29 14:26
It’s not merged with main branch yet. Did you try with the specific branch?

**Comment by nobiot** [comment] 2020-11-29 15:03
If you can wait, I am going to merge the fix branch with the next feature branch I am working on. I was hoping to do its show n tell video this weekend, but it is likely to be next week(end) or later. 

The next feature set adds ability to (re)arrange headline levels of transclusion. There are still challenges I didn't anticipate and need to overcome...

**Comment by randomwangran** [comment] 2020-12-03 22:12
> Unfortunately it doesn't work on my emacs

What is your setting with `org-transclusion-include-first-section`?

I also have such experience but after I set it to `t`, the problem gone. Not sure the root causes. If I encounter the same problem, I will report it back with the condition I meet this issue.

```diff
-(setq org-transclusion-include-first-section nil)
+(setq org-transclusion-include-first-section t)
```

**Comment by nobiot** [comment] 2020-12-06 16:03
#39 merges the fix with main. Closing this issue. Let me know (re-open, or new issue) if you are still experiencing issues with Org-ID.

**Closed by nobiot** 2020-12-06 16:03 UTC

**Comment by lytex** [comment] 2020-12-12 19:32
Although I'm still having the issue,  I have found where it's coming from!

I noticed doom emacs took a while to respond after I activated org-mode-transclusion and it printed on the bottom bar:
"Large file detected! Cutting a few corners to improve performance..." which happens to be part of [doom emacs](https://github.com/hlissner/doom-emacs/blob/develop/core/core-editor.el#L57)

If I change my configuration so that I only open a subfolder with way less and smaller org mode files (i.e., org-directory and org-roam-directory point to a smaller subdirectory) transclusion by id works!

**Comment by nobiot** [comment] 2020-12-12 20:52
How large? And if this Doom feature is not used, does ID still work?

**Comment by lytex** [comment] 2020-12-12 22:42
I've opened an issue in doom repo also. The problem is that I have org files with lines above 400 characters, doom detects these files as "Large files" and changes its behavior to avoid being slow.

If by raising `so-long-threshold` I get transclusion by id working, then we can conclude this is because of this doom configuration

Maybe it would be interesting to bring alphapapa to this conversation, since [org-web-tools](https://github.com/alphapapa/org-web-tools) creates files with more than 400 characters per line, which in turn makes doom change its behavior which in turn makes org-transclusion do something strange with id links.

In the meantime I may write some script to split lines larger than 400 chars

**Comment by lytex** [comment] 2020-12-22 10:45
Now I got it working. 

Maybe due to a misconfiguration, I was testing transclusion in a particular folder /org/projects/ts that I don't use daily, and emacs wasn't able to find the transcluded headlines by id, neither when transcluding nor when using `org-open-at-point`

When transcluding files inside /org/projects everything works fine.

**Comment by nobiot** [comment] 2020-12-22 13:04
Great! Thank you for all the reports.
